#!/bin/sh

# Install Harvester
cd /opt/tomcat/webapps
mvn -B -U dependency:copy -DoutputFile=scmharvester.war
sudo ../bin/startup.sh
sleep 20
sudo ../bin/shutdown.sh
rm scmharvester.war
cp web.xml scmharvester/WEB-INF/web.xml
sleep 2
sudo ../bin/startup.sh
