#!/bin/sh
DATA='{"type": "scm:SCMHarvester", "uri": "http://scmharvester/harvester/ldp4j/api/service/"}'
curl -s -X POST -d "$DATA" http://fountain:5002/seeds -H "content-type: application/json"
while [ "$?" = "7" ]
do
    echo 'Fountain is not yet ready...';
    sleep 1;
    curl -s -X POST -d "$DATA" http://fountain:5002/seeds -H "content-type: application/json"
done

