redis:
  hostname: redis
  domainname: localdomain
  build: redis
#  ports:
#    - "6379:6379"  

fountain:
  build: fountain
  hostname: fountain
  domainname: localdomain
#  ports:    
#    - "5002:5002"
#    - "2223:22"
  links:
    - redis:redis
  command: /sbin/my_init

planner:
  build: planner
  hostname: planner
  domainname: localdomain
#  ports:
#    - "5000:5000"
#    - "2224:22"    
  links:
    - scmharvester:scmharvester
    - fountain:fountain
    - redis:redis
  command: /sbin/my_init

enhancer:
  build: enhancer
  hostname: enhancer
  domainname: localdomain
#  ports:    
#    - "9000:5000"
  links:
    - redis:redis
  command: /sbin/my_init
  environment:
    - ENH_GITLAB_IP=192.168.2.2
    - ENH_GITLAB_PORT=80
    - ENH_GITLAB_USER=root
    - ENH_GITLAB_PASS=12345678
    - ENH_REDIS_IP=192.168.2.2
    - ENH_REDIS_PORT=6379
    - ENH_REDIS_DB=0

scmharvester:
  build: scmharvester
  hostname: scmharvester
  domainname: localdomain
  links:
    - enhancer:enhancer
  command: /sbin/my_init

nginx:
  build: nginx
  hostname: nginx
  domainname: localdomain
  links:
    - planner:planner
    - fountain:fountain
    - enhancer:enhancer
    - scmharvester:scmharvester
  ports:
    - "9001:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf



