redis:
  hostname: redis
  domainname: localdomain
  build: redis

fountain:
  build: fountain
  hostname: fountain
  domainname: localdomain
  links:
    - redis:redis
  command: /sbin/my_init

planner:
  build: planner
  hostname: planner
  domainname: localdomain
  links:
    - scmharvester:scmharvester
    - fountain:fountain
    - redis:redis
  command: /sbin/my_init

enhancer:
  build: enhancer
  hostname: enhancer
  domainname: localdomain
  links:
    - redis:redis
  command: /sbin/my_init
  environment:
    - ENH_GITLAB_IP=192.168.2.2
    - ENH_GITLAB_PORT=80
    - ENH_GITLAB_USER=root
    - ENH_GITLAB_PASS=12345678
    - ENH_REDIS_IP=redis
    - ENH_REDIS_PORT=6379
    - ENH_REDIS_DB=0

scmharvester:
  build: scmharvester
  hostname: scmharvester
  domainname: localdomain
  links:
    - enhancer:enhancer
  command: /sbin/my_init

ciharvester:
  build: ciharvester
  hostname: ciharvester
  domainname: localdomain
  command: /sbin/my_init

nginx:
  build: nginx
  hostname: nginx
  domainname: localdomain
  links:
    - planner:planner
    - fountain:fountain
    - enhancer:enhancer
    - scmharvester:scmharvester
    - ciharvester:ciharvester
  ports:
    - "9001:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf



