#!/bin/sh
 
ROOT=$(pwd)
SDHNAME="sdh-api"

Update() {
    cd /usr/lib
    if [ ! -d node_modules/$1 ]
    then
        npm install $1
    else
    	npm update
    fi
    
    sed -i \
        -e "s|\$PLANNER_PORT|$PLANNER_PORT|g" \
        -e "s|\$PLANNER_ADDR|$PLANNER_ADDR|g" \
        -e "s|\$FRAGMNT_PORT|$FRAGMNT_PORT|g" \
        -e "s|\$FRAGMNT_ADDR|$FRAGMNT_ADDR|g" \
    /home/config.json

    sed -i \
        -e "s|\$SDH_API_HOST|$SDH_API_HOST|g" \
    /home/swagger.json

    cd node_modules/$1
    cp /home/config.json node_modules/agora-fragment-js/config.json
    cp /home/swagger.json api/swagger.json
    node index.js &
    cd $ROOT
}

echo "> SDH API"
Update $SDHNAME
