#!/usr/bin/env python

import requests
import time


def post_seed(ty, uri):
	response = requests.post('http://fountain:5002/seeds', json={'type': ty, 'uri': uri})
	print 'Load {} seed: {}'.format(ty, response.status_code)

connected = False
count = 0
while not connected:
	try:
		post_seed('metrics:MetricService', 'http://cimetrics:5003/metrics')		
		connected = True
	except Exception:
                count += 1
                if count > 1:
                    break
		time.sleep(1)
