#!/bin/sh
DATA='{"type": "ci:CIHarvester", "uri": "http://ciharvester/harvester/service/"}'
curl -s -X POST -d "$DATA" http://fountain:5002/seeds -H "content-type: application/json"
while [ "$?" = "7" ]
do
    echo 'Fountain is not yet ready...';
    sleep 1;
    curl -s -X POST -d "$DATA" http://fountain:5002/seeds -H "content-type: application/json"
done

